[tool.poetry]
name = "asynqq"
version = "0.0.1"
description = ""
authors = ["AeonDave"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
