name: Pylint Check Workflow

on: [ push, pull_request ]

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: asynqq
          python-version: 3.11
