name: Pylint Check Workflow

on:
  push:
    branches: [ main ]

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
