name: Ruff Check Workflow

on: [ push, pull_request ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze
        uses: chartboost/ruff-action@v1