name: Ruff Check Workflow

on:
  push:
    branches: [main]

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Lint with Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true
